// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwtK5j5xsK3tEXjvVbDJW-zYyk-r7vjP0',
    appId: '1:463170281842:web:5d1d72a8799691d6a0bdeb',
    messagingSenderId: '463170281842',
    projectId: 'chatapp-40686',
    authDomain: 'chatapp-40686.firebaseapp.com',
    storageBucket: 'chatapp-40686.firebasestorage.app',
    measurementId: 'G-BRX263QKW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHF5as5h1NbW2i7TEYAuU9x3gt9shvia4',
    appId: '1:463170281842:android:2f73e35ced35e631a0bdeb',
    messagingSenderId: '463170281842',
    projectId: 'chatapp-40686',
    storageBucket: 'chatapp-40686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj8YWjM8DeC3rV2UtkIX-eb2zGu790gMU',
    appId: '1:463170281842:ios:7d4f88258f1c92e2a0bdeb',
    messagingSenderId: '463170281842',
    projectId: 'chatapp-40686',
    storageBucket: 'chatapp-40686.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj8YWjM8DeC3rV2UtkIX-eb2zGu790gMU',
    appId: '1:463170281842:ios:7d4f88258f1c92e2a0bdeb',
    messagingSenderId: '463170281842',
    projectId: 'chatapp-40686',
    storageBucket: 'chatapp-40686.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwtK5j5xsK3tEXjvVbDJW-zYyk-r7vjP0',
    appId: '1:463170281842:web:32f389a00a49c480a0bdeb',
    messagingSenderId: '463170281842',
    projectId: 'chatapp-40686',
    authDomain: 'chatapp-40686.firebaseapp.com',
    storageBucket: 'chatapp-40686.firebasestorage.app',
    measurementId: 'G-ZCKJJ52D9F',
  );
}